### ISSUE TITLE
InvalidArgumentError with CPU version of tensorflow

### ISSUE THREAD

**Issue by rinaldiap** [martijnende/jDAS#3]
An error is raised when trying to run a model training. 
This occurs on both MacOS (where DPU/CUDA version of tensorflow is not supported) as well as on Windows (when CUDA is not set up). The issue disappear once CUDA and TensorFlow-gpu are installed, and the training works as expected.

```
The error is the following for the example provided in this repo (Jupyter Notebook "2_retraining_example") :
InvalidArgumentError:  All dimensions except 3 must match. Input 1 has shape [32 11 640 32] and doesn't match input 0 with shape [32 11 32 64].
	 [[node gradient_tape/model_1/concatenate_4/ConcatOffset
 (defined at /Users/rinaldia/opt/anaconda3/envs/iDAS/lib/python3.8/site-packages/keras/optimizer_v2/optimizer_v2.py:464)
]] [Op:__inference_train_function_2508]
```

**Comment by martijnende** [comment]
Thanks for trying this out. It's curious that it works well with TensorFlow GPU, but for the CPU version. I'll try it out next week to see where the problem lies. Just to confirm, you get this error with [this unmodified example](https://github.com/martijnende/jDAS/blob/master/examples/2_retraining_example.ipynb), correct?

**Comment by rinaldiap** [comment]
Yes exactly!

To make it work on Windows (through PyCharm), I had to make a very minor modification to the jDAS/_init_.py
My system was not finding keras, so I have modified line 3 from "import keras" with "from tensorflow import keras".
But I guess this is linked to my configuration rather than a general problem.

**Comment by martijnende** [comment]
I think I found the problem. Could you do a `git pull origin bug/dataloader_size && git checkout bug/dataloader_size` to see if this fixes your problem?

**Comment by rinaldiap** [comment]
Great it works now! thanks for fixing it! This will enable doing testing on my laptop before using it on cluster/GPUs

**Comment by martijnende** [comment]
Ok, I'll merge this with the main branch then.

The problem of the dataloader should also have appeared on GPU, but perhaps owing to a different "chunking" protocol no exception was raised with `tensorflow-gpu`. Regardless, I'm glad that you reported this bug, for it would affect everyone who wants to retrain the jDAS model.
