### ISSUE TITLE
The scope of application of the model

### ISSUE THREAD

**Issue by fengyanpin** [martijnende/jDAS#5]
Hello, I am very interested in your model, may I ask whether this model is effective for DAS to detect vehicle signals? Is data preprocessing necessary for training with this model?

**Comment by martijnende** [comment]
Hi. This denoising model does not do detection/classification directly, but it could facilitate these tasks by improving the signal-to-noise ratio. If your data contain high levels of incoherent noise, processing them with this model could help to lift the coherent traffic signals out of the noise. A dedicated detector/classifier could then be applied to these denoised data.

If you train the model on "raw" (unprocessed) data, then no additional processing is needed, but if your signals of interest occupy a specific frequency band, the model output could be greatly improved with a bit of pre-processing (like bandpass filtering). It is also recommended to do a bit of post-processing to remove long-period artifacts that the model might introduce.

**Comment by fengyanpin** [comment]
Thank you very much for your guidance. I have standardized the data and band-pass filtering, and then I plan to use your model to denoise.
